version: "3.8"

services:
  fiftyone:
    restart: unless-stopped
    build: .
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - "/home/nick/fiftyone:/root/fiftyone"

volumes:
  fiftyone:
