#!/usr/bin/env bash

# Run a one-shot test with the Cog CLI
cog predict -i prompt="Describe this image." -i image="https://3.bp.blogspot.com/_bVtGlUaW-tA/TIYjKLOSIfI/AAAAAAAAOFg/NjhGhwLBWcE/s1600/3.jpg"

# Alternatively run an endpoint and poll
# https://github.com/replicate/cog/blob/main/docs/deploy.md#getting-started
# docker run -d -p 5001:5000 --gpus all -e HF_HOME=/model-cache -e TORCH_DTYPE=torch.float16 --memory=8g --shm-size=2g r8.im/jimothyjohn/phi3-vision-instruct
# curl http://localhost:5001/predictions -X POST --header "Content-Type: application/json" --data '{"input": {"prompt": "Tell me a possible story about this image.", "image_urls": "https://3.bp.blogspot.com/_bVtGlUaW-tA/TIYjKLOSIfI/AAAAAAAAOFg/NjhGhwLBWcE/s1600/3.jpg"}}' | jq -r '"Output: \(.output)\nPrediction time: \(.metrics.predict_time)s"'
